import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useNavigation } from "@react-navigation/native";
import { useSession } from "../../context/SessionContext";
import { getStudentStats, getUpcomingEvents } from "../../services/events";
import { ApiError } from "../../api/client";
import type { Event, StudentStats } from "../../types/api";
import { EventCard } from "../../components/EventCard";
import { colors, radius, shadow, spacing } from "../../theme/theme";

export function HomeScreen() {
  const { user, signOut } = useSession(); const navigation = useNavigation<any>(); const [events, setEvents] = useState<Event[]>([]); const [stats, setStats] = useState<StudentStats | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setError(""); try { const [eventData, statsData] = await Promise.all([getUpcomingEvents(), user?.role === "student" ? getStudentStats() : Promise.resolve(null)]); setEvents(eventData); setStats(statsData); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load the CampusVerse dashboard."); } finally { setLoading(false); setRefreshing(false); } }, [user?.role]);
  useEffect(() => { load(); }, [load]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.primary} />}>
    <View style={styles.welcome}><View><Text style={styles.eyebrow}>CAMPUSVERSE</Text><Text style={styles.greeting}>Hello, {user?.name || user?.userId || "Student"}</Text><Text style={styles.subtext}>{user?.role === "student" ? "Your campus activity at a glance" : `Signed in as ${user?.role?.replace("_", " ")}`}</Text></View><Pressable onPress={() => signOut()}><Text style={styles.logout}>Logout</Text></Pressable></View>
    {user?.must_change_password && <View style={styles.warning}><Text style={styles.warningTitle}>Password update required</Text><Text style={styles.warningText}>Please update your password on the web portal before using protected role features.</Text></View>}
    {stats && <View style={styles.statsRow}><Stat label="Registered" value={stats.eventsRegistered} /><Stat label="Attended" value={stats.eventsAttended} /><Stat label="Certificates" value={stats.certificatesEarned} /></View>}
    <View style={styles.sectionHeader}><View><Text style={styles.sectionTitle}>Upcoming events</Text><Text style={styles.sectionCopy}>Live from CampusVerse</Text></View><Pressable onPress={() => navigation.navigate("Events")}><Text style={styles.link}>View all</Text></Pressable></View>
    {loading ? <View style={styles.center}><ActivityIndicator color={colors.primary} size="large" /></View> : error ? <View style={styles.errorBox}><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => load()} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View> : events.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No upcoming events</Text><Text style={styles.emptyCopy}>Check back soon for new CampusVerse activities.</Text></View> : events.slice(0, 2).map((event) => <EventCard key={event._id} event={event} onPress={() => navigation.navigate("EventDetail", { event })} />)}
  </ScrollView>;
}
function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.md, paddingBottom: spacing.xxl }, welcome: { paddingTop: spacing.md, paddingBottom: spacing.xl, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, eyebrow: { color: colors.accent, fontWeight: "800", letterSpacing: 1.2, fontSize: 11 }, greeting: { color: colors.text, fontSize: 27, fontWeight: "800", marginTop: 4 }, subtext: { color: colors.mutedText, marginTop: 4, fontSize: 14 }, logout: { color: colors.primary, fontWeight: "700", marginTop: 7 }, warning: { backgroundColor: "#FFF6DB", borderRadius: radius.md, padding: spacing.md, borderWidth: 1, borderColor: "#F5D87E", marginBottom: spacing.md }, warningTitle: { color: "#825700", fontWeight: "800" }, warningText: { color: "#825700", fontSize: 13, lineHeight: 18, marginTop: 3 }, statsRow: { flexDirection: "row", gap: 8, marginBottom: spacing.xl }, stat: { flex: 1, backgroundColor: colors.surface, borderRadius: radius.md, padding: 12, borderWidth: 1, borderColor: colors.border, ...shadow }, statValue: { color: colors.primary, fontSize: 23, fontWeight: "800" }, statLabel: { color: colors.mutedText, fontSize: 11, fontWeight: "600", marginTop: 2 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", marginBottom: spacing.md }, sectionTitle: { color: colors.text, fontSize: 21, fontWeight: "800" }, sectionCopy: { color: colors.mutedText, fontSize: 13, marginTop: 2 }, link: { color: colors.primary, fontWeight: "800", fontSize: 14 }, center: { height: 200, alignItems: "center", justifyContent: "center" }, errorBox: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, alignItems: "center" }, errorText: { color: colors.destructive, textAlign: "center", lineHeight: 20 }, retry: { backgroundColor: colors.primaryLight, borderRadius: radius.sm, paddingHorizontal: 14, paddingVertical: 10, marginTop: spacing.md }, retryText: { color: colors.primary, fontWeight: "800" }, empty: { padding: spacing.xl, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, alignItems: "center" }, emptyTitle: { color: colors.text, fontWeight: "800", fontSize: 16 }, emptyCopy: { color: colors.mutedText, marginTop: 4, textAlign: "center" } });
