// ─────────────────────────────────────────────────────────────
//  SEED DATA — edit this file, then run: node seedAll.js
// ─────────────────────────────────────────────────────────────

export const INSTITUTES = [
  { name: "MIT School of Engineering and Sciences",            code: "SOES"   },
  { name: "MIT School of Computing",                          code: "SOC"    },
  { name: "MIT School of Bioengineering Sciences and Research", code: "SBSR" },
  { name: "MIT School of Food Technology",                    code: "SFT"    },
  { name: "MIT Institute of Design",                          code: "MITID"  },
  { name: "MIT School of Architecture",                       code: "SOA"    },
  { name: "MIT School of Fine Arts and Applied Arts",         code: "SFAA"   },
  { name: "MIT School of Film and Theater",                   code: "SFT2"   },
  { name: "MIT Vishwashanti Sangeet Kala Academy",            code: "VSKA"   },
  { name: "MIT International School of Broadcasting and Journalism", code: "ISBJ" },
  { name: "MIT College of Management",                        code: "MITCOM" },
  { name: "MIT School of Law",                                code: "MITSL"  },
  { name: "Maharashtra Academy of Naval Education and Training", code: "MANET" },
  { name: "MIT School of Education and Research",             code: "SER"    },
  { name: "MIT School of Humanities",                         code: "SOH"    },
  { name: "MIT School of Vedic Sciences",                     code: "SVS"    },
  { name: "MIT School of Holistic Development",               code: "SHD"    },
  { name: "MIT School of Indian Civil Services",              code: "SICS"   },
];

export const CLUBS = [
  { name: "Cognisance",                                        institute_code: null },
  { name: "The Infusion Club",                                 institute_code: null },
  { name: "SAE Collegiate Club",                               institute_code: null },
  { name: "Between The Lines Book Club",                       institute_code: null },
  { name: "MIT CBC",                                           institute_code: null },
  { name: "CINEMANIACS",                                       institute_code: null },
  { name: "MIT Electric Vehicle Club",                         institute_code: null },
  { name: "IDEATE",                                            institute_code: null },
  { name: "Synapse.Ai",                                        institute_code: null },
  { name: "The Psychology Club",                               institute_code: null },
  { name: "SPEEDTAIL RACING",                                  institute_code: null },
  { name: "The Alpha Cell",                                    institute_code: null },
  { name: "MIT ADT Human Library",                             institute_code: null },
  { name: "IGNITE",                                            institute_code: null },
  { name: "Yuvarth",                                           institute_code: null },
  { name: "GDSC",                                              institute_code: null },
  { name: "FOODPRENEURS CLUB",                                 institute_code: null },
  { name: "Cloud Computing Club",                              institute_code: null },
  { name: "MIT ADTU Adventure Club",                           institute_code: null },
  { name: "MIT Swift Coding Club",                             institute_code: null },
  { name: "IEEE Student Branch MIT-ADT",                       institute_code: null },
  { name: "Geeks For Geeks Student Chapter",                   institute_code: null },
  { name: "Institution's Innovation Council",                  institute_code: null },
  { name: "ACES MITSOE",                                       institute_code: null },
  { name: "LEAP OF GRACE",                                     institute_code: null },
  { name: "Codechef",                                          institute_code: null },
  { name: "HERITAGE YATRA",                                    institute_code: null },
  { name: "Laggar Falcon Aero Club",                           institute_code: null },
  { name: "Photography Club",                                  institute_code: null },
  { name: "Painting Club",                                     institute_code: null },
  { name: "Ted-X",                                             institute_code: null },
  { name: "Bikers Community",                                  institute_code: null },
  { name: "Shivraya Dhol Tasha Pathak",                        institute_code: null },
  { name: "Team Volta",                                        institute_code: null },
  { name: "ISBJ Movie Club",                                   institute_code: null },
  { name: "Mechanical Engineering Student Association",         institute_code: null },
  { name: "Samarpan Club",                                     institute_code: null },
  { name: "Hiphop Kanya",                                      institute_code: null },
  { name: "Groovance",                                         institute_code: null },
  { name: "Muse",                                              institute_code: null },
];
